services:
  astor-remote:
    build:
      context: ../
      dockerfile: dev/Dockerfile.remote
    working_dir: /work
    tty: true
    ports:
      - "5005:5005"
    volumes:
      - m2-cache:/root/.m2


volumes:
  m2-cache:
