services:
  astor-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/astor
      - ./work:/work
    working_dir: /work
    tty: true
    ports:
      - "5005:5005"
